//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace.Cbs.Loan.Vew.Properties {
    using System;
    
    
    ///// <summary>
    /////   A strongly-typed resource class, for looking up localized strings, etc.
    ///// </summary>
    //// This class was auto-generated by the StronglyTypedResourceBuilder
    //// class via a tool like ResGen or Visual Studio.
    //// To add or remove a member, edit your .ResX file then rerun ResGen
    //// with the /str option, or rebuild your VS project.
    //[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    //[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    //internal class Resources {
        
    //    private static global::System.Resources.ResourceManager resourceMan;
        
    //    private static global::System.Globalization.CultureInfo resourceCulture;
        
    //    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    //    internal Resources() {
    //    }
        
    //    /// <summary>
    //    ///   Returns the cached ResourceManager instance used by this class.
    //    /// </summary>
    //    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    //    internal static global::System.Resources.ResourceManager ResourceManager {
    //        get {
    //            if (object.ReferenceEquals(resourceMan, null)) {
    //                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ace.Cbs.Loan.Vew.Properties.Resources", typeof(Resources).Assembly);
    //                resourceMan = temp;
    //            }
    //            return resourceMan;
    //        }
    //    }
        
    //    /// <summary>
    //    ///   Overrides the current thread's CurrentUICulture property for all
    //    ///   resource lookups using this strongly typed resource class.
    //    /// </summary>
    //    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    //    internal static global::System.Globalization.CultureInfo Culture {
    //        get {
    //            return resourceCulture;
    //        }
    //        set {
    //            resourceCulture = value;
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap cancel_01 {
    //        get {
    //            object obj = ResourceManager.GetObject("cancel_01", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap Delete_Main {
    //        get {
    //            object obj = ResourceManager.GetObject("Delete_Main", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap edit {
    //        get {
    //            object obj = ResourceManager.GetObject("edit", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap Edit_Main {
    //        get {
    //            object obj = ResourceManager.GetObject("Edit_Main", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap find1 {
    //        get {
    //            object obj = ResourceManager.GetObject("find1", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap Log_Out_16x16 {
    //        get {
    //            object obj = ResourceManager.GetObject("Log Out_16x16", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap Money_Calculator {
    //        get {
    //            object obj = ResourceManager.GetObject("Money_Calculator", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
        
    //    internal static System.Drawing.Bitmap refresh {
    //        get {
    //            object obj = ResourceManager.GetObject("refresh", resourceCulture);
    //            return ((System.Drawing.Bitmap)(obj));
    //        }
    //    }
    //}
}
